# Configuración de la primera base de datos
spring.datasource.url=jdbc:mysql://172.17.0.2:3306/transportesintdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración común de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false


# Configuración de la primera base de datos
#spring.datasource.url=jdbc:mysql://10.10.11.10:3306/transportesintdb?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=Soluciones01
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración común de JPA
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true

