 # Cambiar en base a credenciales de la base de datos donde se  
# alojan las credenciales los choferes
#spring.datasource.url=jdbc:mysql://172.17.0.2:3306/transportesintdb?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Produccion
spring.datasource.url=jdbc:mysql://10.10.11.10:3306/transportesintdb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Soluciones01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración común de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
#server.port=8081

# Credenciales de AWS
#aws.accessKeyId=AKIAXBZV5IMHASBBZD3E
#aws.secretKey=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
#aws.region=us-east-2
#aws.s3.bucketName=evidenciaswebmht
 


